-- =====================================================
-- UnicornSwipe CSV Data Import Script
-- =====================================================
-- Run this AFTER creating the database schema
-- This will import all 120 startup pitches from your CSV file

-- First, ensure the table is ready
-- (This should already exist if you ran database-schema.sql)

-- Import startup pitches from your CSV data
INSERT INTO unicornswipe_startup_pitches (id, pitch, is_seed, category, source) VALUES
(1, 'An AI that drafts cold emails based on LinkedIn profiles.', true, 'AI', 'seed_data'),
(2, 'Uber for blood donations, matching hospitals to nearby donors in real-time.', true, 'Healthcare', 'seed_data'),
(3, 'A Chrome extension that replaces LinkedIn buzzwords with insults.', true, 'Social', 'seed_data'),
(4, 'Subscription service for pre-cooked, bodybuilder-approved meals by top fitness influencers.', true, 'Food', 'seed_data'),
(5, 'A tool that reverse-engineers viral tweets and suggests edits to your posts.', true, 'Social', 'seed_data'),
(6, 'SaaS that generates pitch decks based on your Notion doc.', true, 'SaaS', 'seed_data'),
(7, 'A co-founder matching platform based on MBTI and founder trauma.', true, 'Social', 'seed_data'),
(8, 'Zoom plugin that adds "boredom detection" to your face during calls.', true, 'Productivity', 'seed_data'),
(9, 'An app that lets friends invest in your personal goals like a mini-VC.', true, 'Social', 'seed_data'),
(10, 'Generative AI for YouTube thumbnails that guarantee clicks or your money back.', true, 'AI', 'seed_data'),
(11, 'OnlyFans for startups: pay to see their real burn rate.', true, 'Cursed', 'seed_data'),
(12, 'A meditation app that screams at you until you calm down.', true, 'Wellness', 'seed_data'),
(13, 'Smart toilet that analyzes your mood based on poop frequency.', true, 'Cursed', 'seed_data'),
(14, 'NFTs of parking tickets you never paid. Collect them all.', true, 'Cursed', 'seed_data'),
(15, 'An AI that gives you startup advice... then insults you for following it.', true, 'AI', 'seed_data'),
(16, 'Wearable that shocks you if you open Twitter during work hours.', true, 'Productivity', 'seed_data'),
(17, 'A dating app that matches you based on your Amazon purchase history.', true, 'Social', 'seed_data'),
(18, 'Zoom for dogs. Just dogs barking at each other. Monthly plan $29.', true, 'Cursed', 'seed_data'),
(19, 'A social network where everyone''s anonymous... including you. You don''t know who *you* are.', true, 'Social', 'seed_data'),
(20, 'Marketplace for unused startup domains that sound fake but might work.', true, 'Marketplace', 'seed_data'),
(21, 'A micro-SaaS that helps freelancers with recurring invoice tracking.', true, 'SaaS', 'seed_data'),
(22, 'A startup that does literally nothing but deepfakes of your future self.', true, 'AI', 'seed_data'),
(23, 'A Chrome extension that trolls your fake VC meetings to boost morale.', true, 'Productivity', 'seed_data'),
(24, 'A cursed AI that insists on mood detection in your coffee.', true, 'Cursed', 'seed_data'),
(25, 'An AI that automates pitch deck creation from idea only.', true, 'AI', 'seed_data'),
(26, 'A no-code platform to launch recurring invoice tracking.', true, 'SaaS', 'seed_data'),
(27, 'A micro-SaaS that helps freelancers with project deadlines.', true, 'SaaS', 'seed_data'),
(28, 'A service that sends passive-aggressive pitching your startup to your mom.', true, 'Social', 'seed_data'),
(29, 'A startup that does literally nothing but mood detection in your coffee.', true, 'Cursed', 'seed_data'),
(30, 'A tool that simplifies calendar scheduling across time zones.', true, 'Productivity', 'seed_data'),
(31, 'A wearable that monitors your deepfakes of your future self.', true, 'Cursed', 'seed_data'),
(32, 'A startup that does literally nothing but blockchain-based divorce arbitration.', true, 'Cursed', 'seed_data'),
(33, 'A marketplace for haunted deepfakes of your future self.', true, 'Cursed', 'seed_data'),
(34, 'A SaaS that generates pitch deck creation from idea only.', true, 'SaaS', 'seed_data'),
(35, 'A no-code platform to launch client onboarding flow.', true, 'SaaS', 'seed_data'),
(36, 'An app for tracking cash runway and burn rate.', true, 'SaaS', 'seed_data'),
(37, 'A SaaS that generates equity planning for remote teams.', true, 'SaaS', 'seed_data'),
(38, 'A tool that simplifies real-time competitor tracking.', true, 'SaaS', 'seed_data'),
(39, 'An AI that roasts your pitching your startup to your mom.', true, 'AI', 'seed_data'),
(40, 'An app for tracking recurring invoice tracking.', true, 'SaaS', 'seed_data'),
(41, 'A service that helps founders with founder mental health support.', true, 'Wellness', 'seed_data'),
(42, 'A Chrome extension that trolls your LinkedIn cringe detection.', true, 'Social', 'seed_data'),
(43, 'A dashboard for early-stage founders to monitor client onboarding flow.', true, 'SaaS', 'seed_data'),
(44, 'A marketplace for haunted mood detection in your coffee.', true, 'Cursed', 'seed_data'),
(45, 'A platform that connects calendar scheduling across time zones.', true, 'Productivity', 'seed_data'),
(46, 'An AI that roasts your LinkedIn cringe detection.', true, 'AI', 'seed_data'),
(47, 'A gamified app that rewards users for useless Slack bots.', true, 'Productivity', 'seed_data'),
(48, 'A marketplace for haunted ghosts in abandoned startup offices.', true, 'Cursed', 'seed_data'),
(49, 'An AI that automates founder mental health support.', true, 'AI', 'seed_data'),
(50, 'A B2B tool that optimizes client onboarding flow.', true, 'SaaS', 'seed_data'),
(51, 'A social network for fake VC meetings to boost morale.', true, 'Social', 'seed_data'),
(52, 'A cursed AI that insists on digital twins for your dog.', true, 'Cursed', 'seed_data'),
(53, 'An AI that automates equity planning for remote teams.', true, 'AI', 'seed_data'),
(54, 'A Chrome extension that trolls your useless Slack bots.', true, 'Productivity', 'seed_data'),
(55, 'A wearable that monitors your blockchain-based divorce arbitration.', true, 'Cursed', 'seed_data'),
(56, 'A startup that does literally nothing but digital twins for your dog.', true, 'Cursed', 'seed_data'),
(57, 'A service that sends passive-aggressive useless Slack bots.', true, 'Productivity', 'seed_data'),
(58, 'A cursed AI that insists on blockchain-based divorce arbitration.', true, 'Cursed', 'seed_data'),
(59, 'A service that helps founders with equity planning for remote teams.', true, 'SaaS', 'seed_data'),
(60, 'An AI that roasts your fake VC meetings to boost morale.', true, 'AI', 'seed_data'),
(61, 'A SaaS that generates real-time competitor tracking.', true, 'SaaS', 'seed_data'),
(62, 'An app for tracking beta tester feedback loops.', true, 'SaaS', 'seed_data'),
(63, 'A no-code platform to launch cash runway and burn rate.', true, 'SaaS', 'seed_data'),
(64, 'A B2B tool that optimizes project deadlines.', true, 'SaaS', 'seed_data'),
(65, 'A fridge magnet that screams when you ghosts in abandoned startup offices.', true, 'Cursed', 'seed_data'),
(66, 'A gamified app that rewards users for LinkedIn cringe detection.', true, 'Social', 'seed_data'),
(67, 'A fridge magnet that screams when you blockchain-based divorce arbitration.', true, 'Cursed', 'seed_data'),
(68, 'An AI that roasts your daily startup rejections.', true, 'AI', 'seed_data'),
(69, 'A service that helps founders with pitch deck creation from idea only.', true, 'SaaS', 'seed_data'),
(70, 'A tool that simplifies equity planning for remote teams.', true, 'SaaS', 'seed_data'),
(71, 'A fridge magnet that screams when you digital twins for your dog.', true, 'Cursed', 'seed_data'),
(72, 'A gamified app that rewards users for daily startup rejections.', true, 'Social', 'seed_data'),
(73, 'A tool that simplifies pitch deck creation from idea only.', true, 'SaaS', 'seed_data'),
(74, 'A social network for useless Slack bots.', true, 'Social', 'seed_data'),
(75, 'A social network for daily startup rejections.', true, 'Social', 'seed_data'),
(76, 'An AI that automates real-time competitor tracking.', true, 'AI', 'seed_data'),
(77, 'A service that helps founders with real-time competitor tracking.', true, 'SaaS', 'seed_data'),
(78, 'A dashboard for early-stage founders to monitor recurring invoice tracking.', true, 'SaaS', 'seed_data'),
(79, 'A dashboard for early-stage founders to monitor project deadlines.', true, 'SaaS', 'seed_data'),
(80, 'A dashboard for early-stage founders to monitor cash runway and burn rate.', true, 'SaaS', 'seed_data'),
(81, 'A dashboard for early-stage founders to monitor beta tester feedback loops.', true, 'SaaS', 'seed_data'),
(82, 'A B2B tool that optimizes cash runway and burn rate.', true, 'SaaS', 'seed_data'),
(83, 'A gamified app that rewards users for fake VC meetings to boost morale.', true, 'Social', 'seed_data'),
(84, 'A wearable that monitors your ghosts in abandoned startup offices.', true, 'Cursed', 'seed_data'),
(85, 'A platform that connects founder mental health support.', true, 'Wellness', 'seed_data'),
(86, 'A gamified app that rewards users for pitching your startup to your mom.', true, 'Social', 'seed_data'),
(87, 'A fridge magnet that screams when you mood detection in your coffee.', true, 'Cursed', 'seed_data'),
(88, 'A service that sends passive-aggressive fake VC meetings to boost morale.', true, 'Social', 'seed_data'),
(89, 'A platform that connects pitch deck creation from idea only.', true, 'SaaS', 'seed_data'),
(90, 'A startup that does literally nothing but ghosts in abandoned startup offices.', true, 'Cursed', 'seed_data'),
(91, 'A fridge magnet that screams when you deepfakes of your future self.', true, 'Cursed', 'seed_data'),
(92, 'A platform that connects equity planning for remote teams.', true, 'SaaS', 'seed_data'),
(93, 'An app for tracking client onboarding flow.', true, 'SaaS', 'seed_data'),
(94, 'A SaaS that generates calendar scheduling across time zones.', true, 'SaaS', 'seed_data'),
(95, 'A wearable that monitors your digital twins for your dog.', true, 'Cursed', 'seed_data'),
(96, 'A no-code platform to launch project deadlines.', true, 'SaaS', 'seed_data'),
(97, 'A wearable that monitors your mood detection in your coffee.', true, 'Cursed', 'seed_data'),
(98, 'An AI that automates calendar scheduling across time zones.', true, 'AI', 'seed_data'),
(99, 'A SaaS that generates founder mental health support.', true, 'SaaS', 'seed_data'),
(100, 'A cursed AI that insists on deepfakes of your future self.', true, 'Cursed', 'seed_data'),
(101, 'A micro-SaaS that helps freelancers with cash runway and burn rate.', true, 'SaaS', 'seed_data'),
(102, 'A marketplace for haunted blockchain-based divorce arbitration.', true, 'Cursed', 'seed_data'),
(103, 'A micro-SaaS that helps freelancers with client onboarding flow.', true, 'SaaS', 'seed_data'),
(104, 'A no-code platform to launch beta tester feedback loops.', true, 'SaaS', 'seed_data'),
(105, 'A service that sends passive-aggressive daily startup rejections.', true, 'Social', 'seed_data'),
(106, 'A service that sends passive-aggressive LinkedIn cringe detection.', true, 'Social', 'seed_data'),
(107, 'A social network for LinkedIn cringe detection.', true, 'Social', 'seed_data'),
(108, 'A tool that simplifies founder mental health support.', true, 'Wellness', 'seed_data'),
(109, 'A social network for pitching your startup to your mom.', true, 'Social', 'seed_data'),
(110, 'A marketplace for haunted digital twins for your dog.', true, 'Cursed', 'seed_data'),
(111, 'A Chrome extension that trolls your daily startup rejections.', true, 'Productivity', 'seed_data'),
(112, 'A B2B tool that optimizes beta tester feedback loops.', true, 'SaaS', 'seed_data'),
(113, 'A service that helps founders with calendar scheduling across time zones.', true, 'SaaS', 'seed_data'),
(114, 'An app for tracking project deadlines.', true, 'SaaS', 'seed_data'),
(115, 'A platform that connects real-time competitor tracking.', true, 'SaaS', 'seed_data'),
(116, 'A B2B tool that optimizes recurring invoice tracking.', true, 'SaaS', 'seed_data'),
(117, 'An AI that roasts your useless Slack bots.', true, 'AI', 'seed_data'),
(118, 'A micro-SaaS that helps freelancers with beta tester feedback loops.', true, 'SaaS', 'seed_data'),
(119, 'A cursed AI that insists on ghosts in abandoned startup offices.', true, 'Cursed', 'seed_data'),
(120, 'A Chrome extension that trolls your pitching your startup to your mom.', true, 'Social', 'seed_data');

-- Update the sequence to continue from the last inserted ID
SELECT setval('unicornswipe_startup_pitches_id_seq', (SELECT MAX(id) FROM unicornswipe_startup_pitches));

-- Verify the import
SELECT 
    COUNT(*) as total_pitches,
    COUNT(CASE WHEN category = 'AI' THEN 1 END) as ai_pitches,
    COUNT(CASE WHEN category = 'SaaS' THEN 1 END) as saas_pitches,
    COUNT(CASE WHEN category = 'Cursed' THEN 1 END) as cursed_pitches,
    COUNT(CASE WHEN category = 'Social' THEN 1 END) as social_pitches,
    COUNT(CASE WHEN category = 'Productivity' THEN 1 END) as productivity_pitches
FROM unicornswipe_startup_pitches 
WHERE source = 'seed_data';

SELECT 'Startup pitches imported successfully! 🚀' as status; 